ALTER TABLE team ALTER COLUMN id_season SET NOT NULL;

ALTER TABLE round ALTER COLUMN id_season SET NOT NULL;

ALTER TABLE match ALTER COLUMN id_season SET NOT NULL;

ALTER TABLE match_team ALTER COLUMN id_season SET NOT NULL;
